/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.RECUPERACIONES;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // Creamos el objeto scanner para leer datos del teclado
        Scanner teclado = new Scanner(System.in);

        System.out.println("=========================================");
        System.out.println("     CÁLCULO DE LA HIPOTENUSA            ");
        System.out.println("=========================================");

        // 1. Solicitar el primer cateto
        System.out.print("Ingrese la longitud del Cateto A: ");
        double catetoA = teclado.nextDouble();

        // 2. Solicitar el segundo cateto
        System.out.print("Ingrese la longitud del Cateto B: ");
        double catetoB = teclado.nextDouble();

        // 3. Aplicar la fórmula del Teorema de Pitágoras: c = √(a² + b²)
        // Math.pow(base, exponente) eleva al cuadrado
        // Math.sqrt(numero) calcula la raíz cuadrada
        double hipotenusa = Math.sqrt(Math.pow(catetoA, 2) + Math.pow(catetoB, 2));

        // 4. Mostrar los resultados en pantalla
        System.out.println("-----------------------------------------");
        System.out.println("RESULTADOS:");
        System.out.println("-> Cateto A introducido: " + catetoA);
        System.out.println("-> Cateto B introducido: " + catetoB);
        System.out.println("-> El valor de la Hipotenusa es: " + hipotenusa);
        System.out.println("=========================================");

        // Cerramos el scanner
        teclado.close();
    }
}